listener 8883
allow_anonymous true
<<<<<<< HEAD
cafile ca.crt
certfile server.crt
keyfile server.key
=======
cafile C:\Users\USER\Desktop\scadaPROJECT\vsersion.23\ca.crt
certfile C:\Users\USER\Desktop\scadaPROJECT\vsersion.23\server.crt
keyfile C:\Users\USER\Desktop\scadaPROJECT\vsersion.23\server.key
>>>>>>> bff10e62845c2bbf54c03578d85327a7f796ab11
