listener 8883
allow_anonymous true
cafile C:\Users\USER\Desktop\scadaPROJECT\vsersion.23\ca.crt
certfile C:\Users\USER\Desktop\scadaPROJECT\vsersion.23\server.crt
keyfile C:\Users\USER\Desktop\scadaPROJECT\vsersion.23\server.key